//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCasino.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSCasino.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page uses the Google YouTube Restful API to get you the top 10 poker videos in some of the very best categories. Enjoy!.
        /// </summary>
        internal static string About_APIDemos {
            get {
                return ResourceManager.GetString("About_APIDemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shuffles a deck pf playing cards using either the {0} or {1} shuffling algorithms.  Shuffle up to 10,000 times a nd choose from multiple card packs..
        /// </summary>
        internal static string About_CardShuffler {
            get {
                return ResourceManager.GetString("About_CardShuffler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page deals a full round of poker (nine hands) along with the board cards (flop, turn and river) and highlights the winning hand.  Hand histories are collected and analyzed against typical results..
        /// </summary>
        internal static string About_PokerRoom {
            get {
                return ResourceManager.GetString("About_PokerRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page conmpares the {0} and {1} shuffling algorithms. Shuffle up to 1 million times with either a four or six card sample and see the results displayed graphically..
        /// </summary>
        internal static string About_Randomness {
            get {
                return ResourceManager.GetString("About_Randomness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred attempting to create an email message..
        /// </summary>
        internal static string Err_CreatingEmail {
            get {
                return ResourceManager.GetString("Err_CreatingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error has occurred, please contact the portal administrator..
        /// </summary>
        internal static string Err_Internal {
            get {
                return ResourceManager.GetString("Err_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker Playground.
        /// </summary>
        internal static string Err_Source {
            get {
                return ResourceManager.GetString("Err_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred. However, a critical error occurred while recording the exception information. no exception information was gathered. Unfortunately, there is no more information at this time..
        /// </summary>
        internal static string Err_Unhandled {
            get {
                return ResourceManager.GetString("Err_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon EC2 Server, MS SQL Server, C#, Razor Pages, Entity Framework, YouTube RESTFul API.
        /// </summary>
        internal static string InfoPanel_AboutBackendTech {
            get {
                return ResourceManager.GetString("InfoPanel_AboutBackendTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio, DevExpress Component Suite, GIT Hub, Hosted on AWS Elastic Beanstalk.
        /// </summary>
        internal static string InfoPanel_AboutDevEnv {
            get {
                return ResourceManager.GetString("InfoPanel_AboutDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML, CSS, Javascript, JScript.
        /// </summary>
        internal static string InfoPanel_AboutFrontendTech {
            get {
                return ResourceManager.GetString("InfoPanel_AboutFrontendTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About This Page.
        /// </summary>
        internal static string InfoPanel_AboutHeader {
            get {
                return ResourceManager.GetString("InfoPanel_AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend: .
        /// </summary>
        internal static string InfoPanel_HeaderBackendTech {
            get {
                return ResourceManager.GetString("InfoPanel_HeaderBackendTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development: .
        /// </summary>
        internal static string InfoPanel_HeaderDevEnv {
            get {
                return ResourceManager.GetString("InfoPanel_HeaderDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend: .
        /// </summary>
        internal static string InfoPanel_HeaderFrontendTech {
            get {
                return ResourceManager.GetString("InfoPanel_HeaderFrontendTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologies Used:.
        /// </summary>
        internal static string InfoPanel_TechHeader {
            get {
                return ResourceManager.GetString("InfoPanel_TechHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORST BEATS.
        /// </summary>
        internal static string PokerBeats_Caption {
            get {
                return ResourceManager.GetString("PokerBeats_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerBeatsVids.
        /// </summary>
        internal static string PokerBeats_Key {
            get {
                return ResourceManager.GetString("PokerBeats_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker&apos;s Worst Beats.
        /// </summary>
        internal static string PokerBeats_Phrase {
            get {
                return ResourceManager.GetString("PokerBeats_Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREATEST BLUFFS.
        /// </summary>
        internal static string PokerBluffs_Caption {
            get {
                return ResourceManager.GetString("PokerBluffs_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerBluffsVids.
        /// </summary>
        internal static string PokerBluffs_Key {
            get {
                return ResourceManager.GetString("PokerBluffs_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker&apos;s Greatest Bluffs.
        /// </summary>
        internal static string PokerBluffs_Phrase {
            get {
                return ResourceManager.GetString("PokerBluffs_Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string PokerCategoryTitle {
            get {
                return ResourceManager.GetString("PokerCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAZIEST FIGHTS.
        /// </summary>
        internal static string PokerFights_Caption {
            get {
                return ResourceManager.GetString("PokerFights_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerFightsVids.
        /// </summary>
        internal static string PokerFights_Key {
            get {
                return ResourceManager.GetString("PokerFights_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker&apos;s Craziest Fights.
        /// </summary>
        internal static string PokerFights_Phrase {
            get {
                return ResourceManager.GetString("PokerFights_Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIGGEST HANDS.
        /// </summary>
        internal static string PokerHands_Caption {
            get {
                return ResourceManager.GetString("PokerHands_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerHandsVids.
        /// </summary>
        internal static string PokerHands_Key {
            get {
                return ResourceManager.GetString("PokerHands_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker&apos;s Biggest Hands.
        /// </summary>
        internal static string PokerHands_Phrase {
            get {
                return ResourceManager.GetString("PokerHands_Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker&apos;s Top Ten.
        /// </summary>
        internal static string PokerMenuTitle {
            get {
                return ResourceManager.GetString("PokerMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP TEN {0}.
        /// </summary>
        internal static string PokerTopTen {
            get {
                return ResourceManager.GetString("PokerTopTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every developer needs a playground to experiment with new technologies, test design and layout ideas and labor over that pet project that keeps them up at night.  This site is my playground and, as you can see, one of my personal interests is poker, specifically Texas Hold’em..
        /// </summary>
        internal static string Site_About {
            get {
                return ResourceManager.GetString("Site_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send them an email at....
        /// </summary>
        internal static string Site_Contact {
            get {
                return ResourceManager.GetString("Site_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SticklesSoftware@gmail.com.
        /// </summary>
        internal static string Site_Email {
            get {
                return ResourceManager.GetString("Site_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker Playground.
        /// </summary>
        internal static string Site_Name {
            get {
                return ResourceManager.GetString("Site_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! The Poker Playground server is not curently running.  Please aks the site administrator to start it..
        /// </summary>
        internal static string Site_NoServer {
            get {
                return ResourceManager.GetString("Site_NoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Poker Playground.
        /// </summary>
        internal static string Site_Welcome {
            get {
                return ResourceManager.GetString("Site_Welcome", resourceCulture);
            }
        }
    }
}
